version: "3.8"

services:
  app:
    image: swarmit:latest
    environment:
      DATABASE_URL: "postgres://postgres@database/swarmit"
    ports:
      - 8000:8000
    depends_on:
      - database
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: swarmit
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
