---
database_url: postgres://postgres@/swarmit_test
public_path: "public"

google_oauth_domain: manas.tech
google_oauth_client_id: "347b4b17bec6739951c7e82c1d14b759"
google_oauth_client_secret: "d3df7243fa75d84f8631e4a12b864c13"
google_oauth_redirect_url: "http://test.host/session/callback/google"
